[project]
name = "pyelotl-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elotl>=0.1.1",
    "pandas>=2.2.3",
    "spacy>=3.8.4",
    "spacy-streamlit>=1.0.6",
    "streamlit>=1.49.0",
]
