[project]
name = "pyelotl-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elotl>=0.1.1",
    "pandas>=2.2.3",
    "streamlit>=1.43.1",
]
